\context ChordNames \chords {
	\set Score.markFormatter = #format-mark-box-numbers

	% intro
	\skip 2*4

	% Hemos entregado...
	\break
	\skip 2*4
	%\break
	\skip 2*4

	% Hemos entregado...
	\break
	\skip 2*4
	%\break
	\skip 2*5

	% Bendito seas, sennor...
	\break
	\skip 2*4
	%\break
	\skip 2*4

	% Bendito seas, sennor...
	\break
	\skip 2*4
	%\break
	\skip 2*5

	% Y ahora, sennor...
	\break
	\skip 2*4
	%\break
	\skip 2*4

	% En el cuerpo y sangre...
	\break
	\skip 2*4
	%\break
	\skip 2*5

	% Bendito seas, sennor...
	\break
	\skip 2*4
	%\break
	\skip 2*4

	% Bendito seas, sennor...
	\break
	\skip 2*4
	%\break
	\skip 2*5

	% Hemos entregado...
	\break
	\skip 2*4
	%\break
	%\skip 2*4
}
