	\context ChordNames 
		\chords { 
		c1 \set majorSevenSymbol = \markup { "maj7" } c1:maj7 
		c1 \set majorSevenSymbol = \markup { "maj7" } c1:maj7 
		%
		c1 g1 a1:m a1:m
		f1 g1 c1 g1
		c1 g1 a1:m a1:m
		f1 g1 c2 g2 f1 f1
		%
		a1:m a1:m f1 f2 s4 fis4 g1 g1 c2 g2 g1
		a1:m a1:m f1 f2 s4 fis4 g1 g1 c2 g2 g1 g1
		%
		c1 g1 a1:m a1:m
		f1 g1 c1 g1
		c1 g1 a1:m a1:m
		f1 g1 c2 g2 f1 f1
		%
		a1:m a1:m f1 f2 s4 fis4 g1 g1 c2 g2 g1
		a1:m a1:m f1 f2 s4 fis4 g1 g1 c2 g2 g1 g1
		%
		c1 g1 a1:m e1:m
		f1 g1 f1 f1
		c1 c1
		}
