	\context ChordNames 
		\chords { 
		c2 \set majorSevenSymbol = \markup { "maj7" } c2:maj7
		c2 \set majorSevenSymbol = \markup { "maj7" } c2:maj7
		%
		c2 g2 a2:m a2:m
		f2 g2 c2 g2
		c2 g2 a2:m a2:m
		f2 g2 c4 g4 f2 f2
		%
		a2:m a2:m f2 f4 s8 fis8 g2 g2 c4 g4 g2
		a2:m a2:m f2 f4 s8 fis8 g2 g2 c4 g4 g2 g2
		%
		c2 g2 a2:m a2:m
		f2 g2 c2 g2
		c2 g2 a2:m a2:m
		f2 g2 c4 g4 f2 f2
		%
		a2:m a2:m f2 f4 s8 fis8 g2 g2 c4 g4 g2
		a2:m a2:m f2 f4 s8 fis8 g2 g2 c4 g4 g2 g2
		%
		c2 g2 a2:m e2:m
		f2 g2 f2 f2
		c2 c2
		}
